FROM python:3.9.5-alpine

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

## Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "mydjangoapi.wsgi"]
